### ISSUE TITLE
EditorFiles catched in Quarantine

### ISSUE THREAD

**Issue by mburgholte** [OpenDigitalSignage/EditorFiles#1]
Hi!
First of all big thanks for your work! 
I have the problem that all EditorFiles are marked as potentially dangerous by Defender or other virus software and are moved directly into quarantine. Is there a remedy for this? I can't see anything objectionable in the scripts.

![image](https://user-images.githubusercontent.com/28727337/233983937-1f874123-d40a-4996-acf2-6e47562f13d7.png)

**Comment by mburgholte** [comment]
After a little journey through autoit, innosetup and codesigning, I figured it out. Can be closed.

**Comment by mcmilk** [comment]
The files are really old currently ;-)
But they work, so I have no need to touch anything... only the "dsbd daemon" itself neede some update... but this should work normally also out of the box. Have fun with it.
